### ISSUE TITLE
error: [Errno 25] Inappropriate ioctl for device (macOS)

### ISSUE THREAD

**Issue by karamellpelle** [gastonsimone/vim-dokumentary#6]
Hi! I use _vim-dokumentary_ with the [cppman](https://github.com/aitjcize/cppman) program (_.vimrc_ setting `let g:dokumentary_docprgs = {'cpp': 'cppman {0}', 'python': '','go': '' }`). I have macOS High Sierra. But I get the error 

    error: [Errno 25] Inappropriate ioctl for device

This also happens using _Neovim_. It worked on my Linux (haven't used that computer for a while).

**Comment by gastonsimone** [comment]
Hi! Sorry for the late reply.

First, I realised that this problem is mainly on the cppman side. Try running `cppman vector > somefile`. The contents of `somefile` will be the same error message you show.; but you should really get all the documentation in plain text in that file.

This means cppman does not really support standard output. It is expecting to output to a terminal. This does not allow vim-dokumentary to capture its output. So cppman should realise its output is being redirected. Just like the `ls` command does, in order to avoid formatting its output in columns when being redirected.

Apart from that, if this issue is fixed on the `cppman` side, I suggest you set up cppman to use `less` (`cppman -p less`) and your vim-dokumentary like this: `'cpp': 'cppman {0} | col -b'`.

I hope this helps.
